<?php
/**
 * PHP version 7.1
 *
 * @category Integration
 * @package  Intaro\RetailCrm\Model\Bitrix
 * @author   retailCRM <integration@retailcrm.ru>
 * @license  MIT
 * @link     http://retailcrm.ru
 * @see      http://retailcrm.ru/docs
 */
namespace Intaro\RetailCrm\Model\Bitrix;

use Bitrix\Main\Type\DateTime;

/**
 * Class User
 *
 * @package Intaro\RetailCrm\Model\Bitrix
 *
 * @method int getId()
 * @method void setId()
 * @method string getLogin()
 * @method void setLogin()
 * @method string getPassword()
 * @method void setPassword()
 * @method string getEmail()
 * @method void setEmail()
 * @method bool getActive()
 * @method void setActive()
 * @method DateTime getDateRegister()
 * @method void setDateRegister()
 * @method DateTime getDateRegShort()
 * @method void setDateRegShort()
 * @method DateTime getLastLogin()
 * @method void setLastLogin()
 * @method DateTime getLastLoginShort()
 * @method void setLastLoginShort()
 * @method DateTime getLastActivityDate()
 * @method void setLastActivityDate()
 * @method DateTime getTimestampX()
 * @method void setTimestampX()
 * @method string getName()
 * @method void setName()
 * @method string getSecondName()
 * @method void setSecondName()
 * @method string getLastName()
 * @method void setLastName()
 * @method string getTitle()
 * @method void setTitle()
 * @method string getExternalAuthId()
 * @method void setExternalAuthId()
 * @method string getXmlId()
 * @method void setXmlId()
 * @method string getBxUserId()
 * @method void setBxUserId()
 * @method string getConfirmCode()
 * @method void setConfirmCode()
 * @method string getLid()
 * @method void setLid()
 * @method string getLanguageId()
 * @method void setLanguageId()
 * @method int getTimeZoneOffset()
 * @method void setTimeZoneOffset()
 * @method string getPersonalProfession()
 * @method void setPersonalProfession()
 * @method string getPersonalPhone()
 * @method void setPersonalPhone()
 * @method string getPersonalMobile()
 * @method void setPersonalMobile()
 * @method string getPersonalWww()
 * @method void setPersonalWww()
 * @method string getPersonalIcq()
 * @method void setPersonalIcq()
 * @method string getPersonalFax()
 * @method void setPersonalFax()
 * @method string getPersonalPager()
 * @method void setPersonalPager()
 * @method mixed getPersonalStreet()
 * @method void setPersonalStreet()
 * @method string getPersonalMailbox()
 * @method void setPersonalMailbox()
 * @method string getPersonalCity()
 * @method void setPersonalCity()
 * @method string getPersonalState()
 * @method void setPersonalState()
 * @method string getPersonalZip()
 * @method void setPersonalZip()
 * @method string getPersonalCountry()
 * @method void setPersonalCountry()
 * @method DateTime getPersonalBirthday()
 * @method void setPersonalBirthday()
 * @method string getPersonalGender()
 * @method void setPersonalGender()
 * @method int getPersonalPhoto()
 * @method void setPersonalPhoto()
 * @method mixed getPersonalNotes()
 * @method void setPersonalNotes()
 * @method string getWorkCompany()
 * @method void setWorkCompany()
 * @method string getWorkDepartment()
 * @method void setWorkDepartment()
 * @method string getWorkPhone()
 * @method void setWorkPhone()
 * @method string getWorkPosition()
 * @method void setWorkPosition()
 * @method string getWorkWww()
 * @method void setWorkWww()
 * @method string getWorkFax()
 * @method void setWorkFax()
 * @method string getWorkPager()
 * @method void setWorkPager()
 * @method mixed getWorkStreet()
 * @method void setWorkStreet()
 * @method string getWorkMailbox()
 * @method void setWorkMailbox()
 * @method string getWorkCity()
 * @method void setWorkCity()
 * @method string getWorkState()
 * @method void setWorkState()
 * @method string getWorkZip()
 * @method void setWorkZip()
 * @method string getWorkCountry()
 * @method void setWorkCountry()
 * @method mixed getWorkProfile()
 * @method void setWorkProfile()
 * @method int getWorkLogo()
 * @method void setWorkLogo()
 * @method mixed getWorkNotes()
 * @method void setWorkNotes()
 * @method mixed getAdminNotes()
 * @method void setAdminNotes()
 * @method string getShortName()
 * @method void setShortName()
 * @method bool getIsOnline()
 * @method void setIsOnline()
 * @method bool getIsRealUser()
 * @method void setIsRealUser()
 * @method mixed getIndex()
 * @method void setIndex()
 * @method mixed getIndexSelector()
 * @method void setIndexSelector()
 */
class User extends AbstractModelFacade
{
}
